Mercurius.Sparrow.Backstage/Areas/Dynamic/Controllers/ExtensionPropertyController.cs
using System;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.Dynamic.Entities;
using Mercurius.Kernel.Contracts.Dynamic.SearchObjects;
using Mercurius.Kernel.Contracts.Dynamic.Services;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Prime.Core;

namespace Mercurius.Sparrow.Backstage.Areas.Dynamic.Controllers
{
    /// <summary>
    /// 扩展属性管理控制器。
    /// </summary>
    public class ExtensionPropertyController : BaseController
    {
        #region 属性

        /// <summary>
        /// 扩展属性服务对象。
        /// </summary>
        public IExtensionPropertyService ExtensionPropertyService { get; set; }

        #endregion

        /// <summary>
        /// 扩展属性列表显示&amp;查找。
        /// </summary>
        /// <param name="so">查询条件</param>
        /// <returns>查询结果视图</returns>
        public ActionResult Index(ExtensionPropertySO so)
        {
            var rsp = this.ExtensionPropertyService.SearchExtensionProperties(so);

            this.ViewBag.Categories = this.ExtensionPropertyService.GetCategories();

            return View(rsp);
        }

        /// <summary>
        /// 扩展属性查找。
        /// </summary>
        /// <param name="so">查询条件</param>
        /// <returns>查找结果部分视图</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Search(ExtensionPropertySO so)
        {
            var rsp = this.ExtensionPropertyService.SearchExtensionProperties(so);

            return PartialView("_Properties", rsp);
        }

        /// <summary>
        /// 获取分组信息。
        /// </summary>
        /// <param name="id">扩展属性编号</param>
        /// <returns>分组信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult GetGroupNames(string id)
        {
            var rsp = this.ExtensionPropertyService.GetGroupNames(id);

            return Json(rsp);
        }

        /// <summary>
        /// 添加或修改扩展属性信息。
        /// </summary>
        /// <param name="id">编号</param>
        /// <param name="category">分类</param>
        /// <returns>显示视图</returns>
        public ActionResult CreateOrUpdate(Guid? id = null, string category = null)
        {
            this.ViewBag.Categories = this.ExtensionPropertyService.GetCategories();

            if (id.HasValue)
            {
                var rsp = this.ExtensionPropertyService.GetExtensionPropertyById(id.Value);

                return View(rsp.Data);
            }

            this.ViewBag.Category = category;

            return View();
        }

        /// <summary>
        /// 保存扩展属性信息。
        /// </summary>
        /// <param name="model">扩展属性信息</param>
        /// <returns>保存结果提示</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrUpdate(ExtensionProperty model)
        {
            model.Initialize();

            var rsp = this.ExtensionPropertyService.CreateOrUpdate(model);

            return rsp.IsSuccess ? CloseDialogWithAlert("添加成功！", callback: $"top.main.ReSearch('{model.Category}');") : Alert("添加失败，失败原因：" + rsp.ErrorMessage, AlertType.Error);
        }

        /// <summary>
        /// 删除扩展属性信息。
        /// </summary>
        /// <param name="id">编号</param>
        /// <returns>删除结果信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Remove(Guid id)
        {
            var rsp = this.ExtensionPropertyService.Remove(id);

            return Json(rsp);
        }

        /// <summary>
        /// 保存扩展属性信息。
        /// </summary>
        /// <param name="id">业务逻辑编号</param>
        /// <param name="instances">扩展属性信息列表</param>
        /// <returns>保存结果提示</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult SaveProperties(string id, ExtensionPropertyInstance[] instances)
        {
            if (instances.IsEmpty())
            {
                return Alert("无保存的数据！", AlertType.Waring);
            }

            var index = 0;
            foreach (var item in instances)
            {
                item.Value = this.Request.Form[$"instances[{index++}].Value"];
            }

            var rsp = this.ExtensionPropertyService.CreateInstances(id, instances);

            return rsp.IsSuccess ? AlertWithRefresh("保存成功！") : Alert("保存失败，失败原因：" + rsp.ErrorMessage, AlertType.Error);
        }
    }
}

Mercurius.Sparrow.Backstage/Areas/DynamicPage/Controllers/ExtensionPropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.Dynamic.Entities;
using Mercurius.Kernel.Contracts.Dynamic.SearchObjects;
using Mercurius.Kernel.Contracts.Dynamic.Services;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Prime.Core;

namespace Mercurius.Sparrow.Backstage.Areas.DynamicPage.Controllers
{
    /// <summary>
    /// 扩展属性管理控制器。
    /// </summary>
    public class ExtensionPropertyController : BaseController
    {
        #region 属性

        /// <summary>
        /// 扩展属性服务对象。
        /// </summary>
        public IExtensionPropertyService ExtensionPropertyService { get; set; }

        #endregion

        /// <summary>
        /// 扩展属性列表显示&amp;查找。
        /// </summary>
        /// <param name="so">查询条件</param>
        /// <returns>查询结果视图</returns>
        public ActionResult Index(ExtensionPropertySO so)
        {
            var rsp = this.ExtensionPropertyService.SearchExtensionProperties(so);

            this.ViewBag.Categories = this.ExtensionPropertyService.GetCategories();

            return View(rsp);
        }

        /// <summary>
        /// 扩展属性查找。
        /// </summary>
        /// <param name="so">查询条件</param>
        /// <returns>查找结果部分视图</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Search(ExtensionPropertySO so)
        {
            var rsp = this.ExtensionPropertyService.SearchExtensionProperties(so);

            return PartialView("_Properties", rsp);
        }

        /// <summary>
        /// 获取分组信息。
        /// </summary>
        /// <param name="id">扩展属性编号</param>
        /// <returns>分组信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult GetGroupNames(string id)
        {
            var rsp = this.ExtensionPropertyService.GetGroupNames(id);

            return Json(rsp);
        }

        /// <summary>
        /// 添加或修改扩展属性信息。
        /// </summary>
        /// <param name="id">编号</param>
        /// <param name="category">分类</param>
        /// <returns>显示视图</returns>
        public ActionResult CreateOrUpdate(Guid? id = null, string category = null)
        {
            this.ViewBag.Categories = this.ExtensionPropertyService.GetCategories();

            if (id.HasValue)
            {
                var rsp = this.ExtensionPropertyService.GetExtensionPropertyById(id.Value);

                return View(rsp.Data);
            }

            this.ViewBag.Category = category;

            return View();
        }

        /// <summary>
        /// 保存扩展属性信息。
        /// </summary>
        /// <param name="model">扩展属性信息</param>
        /// <returns>保存结果提示</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrUpdate(ExtensionProperty model)
        {
            model.Initialize();

            var rsp = this.ExtensionPropertyService.CreateOrUpdate(model);

            return rsp.IsSuccess ? CloseDialogWithAlert("添加成功！", callback: $"top.main.ReSearch('{model.Category}');") : Alert("添加失败，失败原因：" + rsp.ErrorMessage, AlertType.Error);
        }

        /// <summary>
        /// 删除扩展属性信息。
        /// </summary>
        /// <param name="id">编号</param>
        /// <returns>删除结果信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Remove(Guid id)
        {
            var rsp = this.ExtensionPropertyService.Remove(id);

            return Json(rsp);
        }

        /// <summary>
        /// 保存扩展属性信息。
        /// </summary>
        /// <param name="id">业务逻辑编号</param>
        /// <param name="instances">扩展属性信息列表</param>
        /// <returns>保存结果提示</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult SaveProperties(string id, ExtensionPropertyInstance[] instances)
        {
            if (instances.IsEmpty())
            {
                return Alert("无保存的数据！", AlertType.Waring);
            }

            var index = 0;
            foreach (var item in instances)
            {
                item.Value = this.Request.Form[$"instances[{index++}].Value"];
            }

            var rsp = this.ExtensionPropertyService.CreateInstances(id, instances);

            return rsp.IsSuccess ? AlertWithRefresh("保存成功！") : Alert("保存失败，失败原因：" + rsp.ErrorMessage, AlertType.Error);
        }
    }
}

Mercurius.Sparrow.Backstage/Areas/Dynamic/Views/ExtensionProperty/CreateOrUpdate.cshtml
@model ExtensionProperty

@{
    var categories = this.ViewBag.Categories as ResponseSet<string>;
}

@section Styles{
    <style type="text/css">
        .select {
            width: 100%;
        }

            .select > .input-group.active > .form-control {
                border-bottom-left-radius: 0;
            }

            .select > .input-group.active > .input-group-btn > .btn {
                border-bottom-right-radius: 0;
            }

            .select > .select-items {
                display: none;
                position: absolute;
                z-index: 999;
                width: 100%;
                left: 5px;
                top: 33px;
                max-height: 300px;
                overflow-y: auto;
                background-color: white;
                border: 1px solid #cccccc;
            }

                .select > .select-items > p {
                    margin: 0;
                    cursor: pointer;
                    padding: 5px 10px;
                }

                    .select > .select-items > p:hover {
                        background: #eee;
                    }
    </style>
}

@section Scripts
{
    @Scripts.Render("~/bundles/validate")
    <script type="text/javascript">
        $(document).ready(function () {
            if ('@(this.ViewBag.Category)' != '') {
                $('#Category').val('@(this.ViewBag.Category)');
            }

            $('#Category').blur(function () {
                InitGroupNames();
            });

            $('#Name').on('input propertychange', function () {
                $('#Placeholder').val($(this).val());
            });

            $('button[nav-target]').click(function () {
                var target = $(this).attr('nav-target');

                if ($(target).has('p').length > 0) {
                    $(target).prev().addClass('active');
                    $(target).width($(target).parent().width() - 2);

                    $(target).slideDown(200);
                }

                return false;
            });

            $('#__categories>p').click(function () {
                $('#Category').val($(this).text());

                InitGroupNames();
            });

            $(document).on('click', function () {
                $('.select-items').slideUp();
                $('.select-items').prev().removeClass('active');
            });

            InitGroupNames();
        });

        function InitGroupNames() {
            $.ajax({
                type: 'POST',
                cache: false,
                url: '@Url.Action("GetGroupNames")',
                data: { id: $('#Category').val() },
                dataType: 'JSON',
                success: function (rs) {
                    $('#__groupNames').html('');

                    if (rs.IsSuccess) {
                        $.each(rs.Datas, function () {
                            $('#__groupNames').append('<p>' + this + '</p>');
                        });

                        $('button[nav-target="#__groupNames"]').prop('disabled', (rs.Datas == null || rs.Datas.length == 0));

                        $('#__groupNames>p').click(function () {
                            $('#GroupName').val($(this).text());
                        });
                    }
                }
            });
        }

        function OnSave() {
            if (JudgeValidate('#frmSave')) {
                $('#frmSave').submit();
            }
        }
    </script>
}
@using (Ajax.BeginForm("CreateOrUpdate", "ExtensionProperty", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "frmSave", @class = "form-horizontal form" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Category, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-9">
            <div class="select">
                <div class="input-group">
                    @Html.TextBoxFor(m => m.Category, new { @class = "form-control", @validate_rule = "notNull" })
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default" nav-target="#__categories" @(categories.HasData() ? "" : "disabled")>
                            <i class="glyphicon glyphicon-chevron-down"></i>
                        </button>
                    </span>
                </div>
                <div id="__categories" class="select-items">
                    @if (categories.HasData())
                    {
                        foreach (var item in categories.Datas)
                        {
                    <p>@item</p>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-4">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @validate_rule = "notNull", @validate_field = "属性名" })
        </div>
        @Html.LabelFor(m => m.Unit, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-3">
            @Html.TextBoxFor(m => m.Unit, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlId, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-4">
            @Html.TextBoxFor(m => m.ControlId, new { @class = "form-control", @validate_rule = "notNull" })
        </div>
        @Html.LabelFor(m => m.GroupName, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-3">
            <div class="select">
                <div class="input-group">
                    @Html.TextBoxFor(m => m.GroupName, new { @class = "form-control" })
                    <span class="input-group-btn">
                        <button type="button" class="btn btn-default" nav-target="#__groupNames">
                            <i class="glyphicon glyphicon-chevron-down"></i>
                        </button>
                    </span>
                </div>
                <div id="__groupNames" class="select-items">
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlType, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-4">
            <select id="ControlType" name="ControlType" class="form-control">
                <option value="1">1-文本框</option>
                <option value="2" @((Model != null && Model.ControlType == 2) ? "selected" : "")>2-下拉框</option>
                <option value="3" @((Model != null && Model.ControlType == 3) ? "selected" : "")>3-单选框</option>
                <option value="4" @((Model != null && Model.ControlType == 4) ? "selected" : "")>4-复选框</option>
            </select>
        </div>
        @Html.LabelFor(m => m.ControlMaxLength, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-3">
            <div class="input-group">
                @Html.TextBoxFor(m => m.ControlMaxLength, new { @class = "form-control", @validate_rule = "intOrNull" })
                <span class="input-group-addon">字符</span>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Placeholder, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-9">
            @Html.TextBoxFor(m => m.Placeholder, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlValidateRule, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-4">
            @Html.CreateValidRuleListFor(m => m.ControlValidateRule)
        </div>
        @Html.LabelFor(m => m.Sort, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-3">
            @Html.TextBoxFor(m => m.Sort, new { @class = "form-control", @validate_rule = "int" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlLabelCssClass, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-4">
            <select name="ControlLabelCssClass" class="form-control">
                @for (var i = 1; i <= 6; i++)
                {
                    <option value="col-sm-@i" data-tag="@i" @((Model != null && Model.ControlLabelCssClass == "col-sm-" + i) ? "selected" : "")>col-sm-@i</option>
                }
            </select>
        </div>
        @Html.LabelFor(m => m.ControlContainerCssClass, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-3">
            <select name="ControlContainerCssClass" class="form-control">
                @for (var i = 2; i <= 11; i++)
                {
                    <option value="col-sm-@i" data-tag="@i" @((Model != null && Model.ControlContainerCssClass == "col-sm-" + i) ? "selected" : "")>col-sm-@i</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlDataSource, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-9">
            @Html.TextAreaFor(m => m.ControlDataSource, new { @class = "form-control", @rows = 3, @placeholder = "多个选项以;分隔(如果需要文本和值不一样，则用\"文本|值\"的形式)。" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ControlStyle, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-9">
            @Html.TextAreaFor(m => m.ControlStyle, new { @class = "form-control", @rows = 3 })
        </div>
    </div>
    if (Model != null)
    {
        <div class="form-group">
            @Html.LabelFor(m => m.CreateDateTime, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.CreateDateTime, new { @class = "form-control", @readonly = "readonly" })
            </div>
            @Html.LabelFor(m => m.CreateUserName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.CreateUserName, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ModifyDateTime, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-4">
                @Html.TextBoxFor(m => m.ModifyDateTime, new { @class = "form-control", @readonly = "readonly" })
            </div>
            @Html.LabelFor(m => m.ModifyUserName, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-3">
                @Html.TextBoxFor(m => m.ModifyUserName, new { @class = "form-control", @readonly = "readonly" })
            </div>
        </div>
    }
}

Mercurius.Sparrow.Backstage/Areas/Dynamic/Views/ExtensionProperty/Index.cshtml
@model ResponseSet<ExtensionProperty>

@{
    var categories = this.ViewBag.Categories as ResponseSet<string>;
}

@section Styles
{
    @Styles.Render("~/Content/tree/css")
}

@section Scripts
{
    @Scripts.Render("~/bundles/tree")
    <script type="text/javascript">
        $(document).ready(function () {
            $('#treeContainer').treeview({
                collapsed: false,
                unique: false
            });

            $('#treeContainer b[data]').click(function() {
                $('#treeContainer b[data]').removeClass('selected');

                ReSearch($(this).attr('data'));

                $(this).addClass('selected');

                return false;
            });

            mercurius.FixedTableHeader('#tbDefinition', 160);
        });

        function ReSearch(category) {
            $.ajax({
                type:'POST',
                cache:false,
                url:'@Url.Action("Search","ExtensionProperty")',
                data:{Category:category},
                dataType:'html',
                success:function(rs) {
                    $('#__properties').html(rs);
                    mercurius.FixedTableHeader('#tbDefinition', 160);
                }
            });
        }

        @Html.RenderButtonScript("添加",@<text>
        function @(item.NavigateUrl)(){
            var category = $('#treeContainer i.selected').attr('data');

            mercurius.OpenDialog('@Url.Action("CreateOrUpdate","ExtensionProperty")?category='+category, 'CreateOrUpdate', '添加动态属性', 650, 430);
        }
        </text>)

        @Html.RenderButtonScript("编辑", @<text>
        function @(item.NavigateUrl)(){
            var id=$('#tbDefinition > tbody > tr.selected > td:eq(0)').text();

            if(mercurius.HasSingleRowSelected(id)){
                mercurius.OpenDialog('@Url.Action("CreateOrUpdate","ExtensionProperty")/'+id, 'CreateOrUpdate', '修改动态属性', 650, 510);
            }
        }
        </text>)

        @Html.RenderButtonScript("删除",@<text>
        function @(item.NavigateUrl)() {
            var id=$('#tbDefinition > tbody > tr.selected > td:eq(0)').text();

            if(mercurius.HasSingleRowSelected(id)) {
                mercurius.RemoveData('@Url.Action("Remove")',{id:id});
            }
        }
        </text>)
    </script>
}
<div class="header">动态属性管理</div>
<div class="row">
    <div class="col-sm-3" style="padding-right: 0;">
        <div class="toolbar panel panel-default" style="min-width: auto;">
            <div class="panel-heading" style="padding-left: 10px; line-height: 35px;">动态属性分类</div>
            <div class="panel-body" style="padding: 0 5px;">
                <ul id="treeContainer" class="filetree">
                    <li>
                        <span class="folder"></span>
                        <b data="" class="text selected">全部分类</b>
                        <ul id="blList">
                            @if (categories.HasData())
                            {
                                foreach (var item in categories.Datas)
                                {
                                    <li>
                                        <span class="file"></span><b class="text" data="@item">@item</b>
                                    </li>
                                }
                            }
                            else
                            {
                                <li class="last">
                                    <span class="file empty-data"></span>无分类信息
                                </li>
                            }
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-9" style="padding-left: 5px;">
        @Html.RenderAccessibleButtons()
        <div id="__properties">
            @{
                Html.RenderPartial("_Properties", Model);}
        </div>
    </div>
</div>

Mercurius.Sparrow.Backstage/Areas/Dynamic/Views/ExtensionProperty/_Properties.cshtml
@model ResponseSet<ExtensionProperty>

<table id="tbDefinition" class="grid">
    <thead>
        <tr>
            <td style="width: 60px;">序号</td>
            <td>分类</td>
            <td>名称(单位)</td>
            <td style="width: 60px;">分组</td>
            <td style="width: 50px;">排序号</td>
            <td style="width: 80px;">类型</td>
            <td>标签css类</td>
            <td>容器css类</td>
            <td>验证类型</td>
        </tr>
    </thead>
    <tbody>
        @if (Model.HasData())
        {
            foreach (var item in Model.Datas)
            {
                <tr>
                    <td style="display: none;">@item.Id</td>
                    <td class="text-center">@item.RowIndex</td>
                    <td>@item.Category</td>
                    <td>@item.Name @(string.IsNullOrWhiteSpace(item.Unit) ? "" : "(" + item.Unit + ")")</td>
                    <td>@item.GroupName</td>
                    <td class="text-center">@item.Sort</td>
                    <td class="text-center">@ShowControlType(item.ControlType)</td>
                    <td>@item.ControlLabelCssClass</td>
                    <td>@item.ControlContainerCssClass</td>
                    <td>@item.ControlValidateRule</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="10" class="empty-data">@Html.GetGlobalValue("empty-data")</td>
            </tr>
        }
    </tbody>
</table>
@Html.Paging(Model.TotalRecords, "Search", "ExtensionProperty", ajaxOptions: new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "__properties", OnSuccess = "mercurius.FixedTableHeader('#tbDefinition', 160);" })

@helper ShowControlType(int type)
{
    switch (type)
    {
        case 1:<text>1-文本框</text>
            break;

        case 2:<text>2-下拉框</text>
            break;
        case 3:<text>3-单选框</text>
            break;
        case 4:<text>4-复选框</text>
            break;
    }
}