Mercurius.Sparrow.Backstage/Areas/Admin/Controllers/LoggerController.cs
using System;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.Core.SearchObjects;
using Mercurius.Kernel.Contracts.Core.Services;
using Mercurius.Kernel.WebCores.Filters;

namespace Mercurius.Sparrow.Backstage.Areas.Admin.Controllers
{
    /// <summary>
    /// 日志管理控制器。
    /// </summary>
    public class LoggerController : BaseController
	{
		#region 属性

		/// <summary>
		/// 日志信息服务对象。
		/// </summary>
		public ILoggerService LoggerService { get; set; }

		#endregion

        /// <summary>
        /// 显示日志列表界面。
        /// </summary>
        /// <returns>显示视图</returns>
		public ActionResult Index()
		{
            this.ViewBag.Logs = this.LoggerService.SearchLogs(new LogSO());

            return this.View();
		}

        /// <summary>
        /// 日志查找。
        /// </summary>
        /// <param name="so">查询条件</param>
        /// <returns>日志列表部分视图</returns>
        [HttpPost]
        [IgnorePermissionValid]
		public ActionResult Search(LogSO so)
		{
			if (so.EndDate.HasValue)
			{
				so.EndDate = DateTime.Parse($"{so.EndDate.Value.ToString("yyyy-MM-dd")} 23:59:59");
			}

            this.ViewBag.SO = so;
			var rsp = this.LoggerService.SearchLogs(so);

			return this.PartialView("_Logs", rsp);
		}

        /// <summary>
        /// 清空日志。
        /// </summary>
        /// <returns>清空结果</returns>
		[HttpPost]
        [IgnorePermissionValid]
        public ActionResult ClearLogs()
		{
			var rsp = this.LoggerService.ClearLogs();

			return this.Json(rsp);
		}

        /// <summary>
        /// 查看日志详情。
        /// </summary>
        /// <param name="partition">分区</param>
        /// <param name="id">日志编号</param>
        /// <returns>显示视图</returns>
		public ActionResult ViewDetails(string partition, string id)
		{
			var model = this.LoggerService.GetLog(partition, id);

			return this.View(model);
		}
	}
}

Mercurius.Sparrow.Backstage/Areas/Admin/Views/Logger/Index.cshtml
@using Mercurius.Prime.Core.Logger
@using Mercurius.Kernel.Contracts.Core.SearchObjects

@model LogSO

@section Styles{
    <style type="text/css">
        .form-inline {
            display: inline-block;
        }

        .control-label {
            margin: 0;
            margin-left: 15px;
        }

        .form-control {
            width: 150px;
            display: inline-block;
        }

        .ShortcutSearch {
            padding-right: 20px;
            padding-left: 10px;
        }

            .ShortcutSearch .brand {
                display: block;
                float: left;
                margin-left: 2px;
                font-weight: bold;
                color: #000;
                padding-top: 9px;
                text-shadow: 0 1px 0 #FFF;
            }

            .ShortcutSearch .btn-danger {
                color: #fff;
            }
    </style>
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            mercurius.ShowDatePicker();
            mercurius.FixedTableHeader("#logsGrid", 200);
        });

        function OnSearchSuccess() {
            mercurius.FixedTableHeader("#logsGrid", 200);
        }

        function ClearLogs() {
            mercurius.ShowConfirmMessage('是否清空所有日志信息？', function () {
                $.ajax({
                    type: 'POST',
                    cache: false,
                    async: false,
                    url: '@Url.Action("ClearLogs")',
                    success: function (rs) {
                        if (rs.IsSuccess) {
                            window.location.href = '@Url.Action("Index")';
                        } else {
                            mercurius.ShowWarningMessage('出现错误，错误详情：' + rs.ErrorMessage);
                        }
                    }
                });
            });
        }

        function ViewDetails() {
            var logId = $('#logsGrid tr.selected').attr('data-id');

            if (mercurius.HasSingleRowSelected(logId)) {
                var url = '@Url.Action("ViewDetails")/' + logId;

                mercurius.OpenDialog(url, 'ViewLogDetails', '查看日志详情', 600, 420, { statusbar: false });
            }
        }
    </script>
}
<div class="header">日志管理</div>
@using (Ajax.BeginForm("Search", "Logger", null, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "logsContainer", OnSuccess = "OnSearchSuccess" }, new { @id = "frmSearch", @class = "form-horizontal form", autocomplete = "off" }))
{
    <div style="margin-top: 8px;">
        @Html.MultipleListFor(m => m.Level, "日志级别", f => f.Label("日志级别").IncludeAll().Style("width:80px;"))
        <label class="control-label" for="StartDate">时间范围</label>
        <div class="form-inline">
            @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control date", style = "width: 100px;" })
            &nbsp;～&nbsp;
            @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control date", style = "width: 100px;" })
        </div>
        @Html.TextBoxFor(m => m.LogOnName, f => f.Label("用户"))
        @Html.TextBoxFor(m => m.LogOnIP, f => f.Label("登录IP"))
        @Html.TextBoxFor(m => m.ModelName, f => f.Label("模块"))
        <span class="btn-group" style="margin: -4px 0 0 0;">
            <button type="submit" class="btn btn-primary">
                <i class="glyphicon glyphicon-search"></i> 查询
            </button>
            <button type="button" class="btn btn-default" onclick="$('#frmSearch input[name],#frmSearch select').val('');">
                <i class="glyphicon glyphicon-remove"></i> 重置
            </button>
        </span>
    </div>
}
<div class="toolbar panel panel-default" style="margin-top: 6px;">
    <div class="panel-heading">
        <div class="right btn-group">
            <a class="btn btn-default" onclick="ClearLogs()">
                <i class="glyphicon glyphicon-trash"></i> 清空日志
            </a>
            <a class="btn btn-default" onclick="ViewDetails()">
                <i class="glyphicon glyphicon-list-alt"></i> 查看详情
            </a>
        </div>
    </div>
</div>
<div id="logsContainer">
    @{
        Html.RenderPartial("_Logs", this.ViewBag.Logs as ResponseSet<Log>);
    }
</div>

Mercurius.Sparrow.Backstage/Areas/Admin/Views/Logger/ViewDetails.cshtml
@using Mercurius.Prime.Core.Logger
@model Response<Log>

@section Styles{
    <style type="text/css">
        .form-horizontal.form .col-sm-10 {
            padding-top: 5px;
        }
    </style>
}
@if (Model != null)
{
    <div class="form-horizontal form">
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">用户</label>
            <div class="col-sm-10">@Model.Data.LogOnName</div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">用户IP地址</label>
            <div class="col-sm-10">@Model.Data.LogOnIP</div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">模块</label>
            <div class="col-sm-10">@Model.Data.ModelName</div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">级别</label>
            <div class="col-sm-10">@Model.Data.Level</div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">记录时间</label>
            <div class="col-sm-10">@Model.Data.OccurrenceDateTime</div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">日志简介</label>
            <div class="col-sm-10">
                <div style="overflow-y:auto; height:40px;">
                    @Model.Data.Summary
                </div>
            </div>
        </div>
        <div class="form-group form-group-sm">
            <label class="col-sm-2 control-label">日志详情</label>
            <div class="col-sm-10">
                <div style="overflow-y:auto; height:210px;">
                    @Html.Raw(Model.Data.ShowValue(c => c.Details))
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="text-danger">没有该日志信息。</div>
}

Mercurius.Sparrow.Backstage/Areas/Admin/Views/Logger/_Logs.cshtml
@using Mercurius.Prime.Core.Logger

@model ResponseSet<Log>

@Html.DataGridFor(Model,
    t => t.Id("logsGrid").ShowLineNumber()
          .RowData("data-id", c => c.Id)
          .Column(c => c.LogOnName, "用户", 120)
          .Column(c => c.LogOnIP, "用户IP地址", 140)
          .Column(c => c.ModelName, "模块", 180)
          .Column(c => c.Level, "级别", 60)
          .Column(c => c.OccurrenceDateTime, "记录时间", 150, "{0:yyyy-MM-dd HH:mm:ss}")
          .Column(c => c.Summary, "日志简介")
          .Paging("Search", "Logger", this.ViewBag.SO, ajaxOptions: new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "logsContainer", OnSuccess = "OnSearchSuccess" })
)