Mercurius.Sparrow.Backstage/Areas/Dynamic/Models/Configuration/CreateOrUpdateColumn.cs
using Mercurius.Kernel.Contracts.Dynamic.Entities;

namespace Mercurius.Sparrow.Backstage.Areas.Dynamic.Models.Configuration
{
    /// <summary>
    /// 添加/编辑列配置信息。
    /// </summary>
    public class CreateOrUpdateColumn : CreateOrUpdateInfo
    {
        #region 属性

        /// <summary>
        /// 列名称。
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 列属性名称。
        /// </summary>
        public string PropertyName { get; set; }

        /// <summary>
        /// 列描述信息。
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// 是否为主键。
        /// </summary>
        public bool IsPrimaryKey { get; set; }

        /// <summary>
        /// 是否为自动增长列。
        /// </summary>
        public bool IsIdentity { get; set; }

        /// <summary>
        /// 是否为可空。
        /// </summary>
        public bool IsNullable { get; set; }

        /// <summary>
        /// 列长度。
        /// </summary>
        public long? DataLength { get; set; }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/Dynamic/Models/Configuration/CreateOrUpdateConfigModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.Core.Entities;
using Mercurius.Prime.Core;
using Mercurius.Prime.Core.Ado;

namespace Mercurius.Sparrow.Backstage.Areas.Dynamic.Models.Configuration
{
    /// <summary>
    /// 添加或编辑动态页面配置模型。
    /// </summary>
    public class CreateOrUpdateConfigModel
    {
        #region 字段

        private IList<Dictionary> _dictionaries;

        #endregion

        #region 属性

        /// <summary>
        /// 表信息。
        /// </summary>
        public Table Table { get; set; }

        /// <summary>
        /// 表的所有列信息。
        /// </summary>
        public IEnumerable<CreateOrUpdateColumn> Columns { get; set; }

        /// <summary>
        /// 字典信息。
        /// </summary>
        public IList<Dictionary> Dictionaries
        {
            get { return this._dictionaries; }
            set
            {
                if (this._dictionaries != value)
                {
                    value.ForEach(d => d.Value = d.Key);

                    this._dictionaries = value;
                }
            }
        }

        #endregion

        #region 公开方法

        /// <summary>
        /// 获取字典分类信息下拉框数据源。
        /// </summary>
        /// <param name="selectedValue">选定的值</param>
        /// <returns>下拉框数据源</returns>
        public IList<SelectListItem> GetDictionaryList(string selectedValue = null)
        {
            var items = new List<SelectListItem>();

            if (!this.Dictionaries.IsEmpty())
            {
                items.Add(new SelectListItem
                {
                    Text = "无",
                    Value = string.Empty
                });

                items.AddRange(this.Dictionaries.Select(item => new SelectListItem
                {
                    Text = item.Key,
                    Value = item.Key,
                    Selected = item.Key == selectedValue
                }));
            }

            return items;
        }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/Dynamic/Controllers/ConfigurationController.cs
using System.Linq;
using System.Web.Mvc;
using Mercurius.Sparrow.Backstage.Areas.Dynamic.Models.Configuration;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Kernel.Contracts.Dynamic.Entities;
using Mercurius.Prime.Core;
using Mercurius.Prime.Core.Ado;
using Mercurius.Kernel.Contracts.Core.Entities;
using Mercurius.Prime.Core.Dynamic;
using System.Collections.Generic;

namespace Mercurius.Sparrow.Backstage.Areas.Dynamic.Controllers
{
    /// <summary>
    /// 动态查询配置控制器。
    /// </summary>
    public class ConfigurationController : BaseController
    {
        /// <summary>
        /// 动态查询配置首页操作。
        /// </summary>
        /// <returns>返回动态查询配置页面</returns>
        public ActionResult Index()
        {
            var model = this.DynamicQuery.Provider.DbMetadata.GetTables();

            return View(model);
        }

        #region 表注释

        /// <summary>
        /// 注解表信息。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="comments">注解信息</param>
        /// <returns>返回注解结果json</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult CommentTable(string id, string comments)
        {
            this.DynamicQuery.Provider.DbMetadata.CommentTable(id, comments);

            return Json(new { Success = true });
        }

        #endregion

        #region 列注释

        /// <summary>
        /// 显示表的所有列信息操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <returns>返回表的所有列信息显示页面</returns>
        public ActionResult ShowColumns(string id)
        {
            this.ViewBag.Table = id;
            var model = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);

            return View(model);
        }

        /// <summary>
        /// 注解表的列信息操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="columns">列信息集合</param>
        /// <returns>返回列注释成功的js提醒</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult CommentColumns(string id, IList<Column> columns)
        {
            if (!columns.IsEmpty())
            {
                foreach (var item in columns)
                {
                    this.DynamicQuery.Provider.DbMetadata.CommentColumn(id, item.Name, item.Description);
                }
            }

            return CloseDialogWithAlert("修改成功！");
        }

        #endregion

        #region 查询配置

        /// <summary>
        /// 显示查询配置的操作。
        /// </summary>
        /// <param name="id">表的名称</param>
        /// <returns>返回显示查询配置的页面</returns>
        public ActionResult ShowSearchConfig(string id)
        {
            var model = new SearchConfigModel
            {
                Table = this.DynamicQuery.Provider.DbMetadata.GetTable(id)
            };

            if (model.Table != null)
            {
                model.Columns = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);
                model.Orders = this.DynamicQuery.Where<OrderInfo>(m => m.TableName, id).List();
                model.Search = this.DynamicQuery.Where<SearchInfo>(m => m.TableName, id).Single();
                model.Conditions = this.DynamicQuery.Where<ConditionInfo>(m => m.TableName, id).List();
                model.Dictionaries = this.DynamicQuery.Where<Dictionary>(m => m.ParentId, null, Op.IsNull).OrderBy(m => m.Sort).List<Dictionary>();
            }

            return View(model);
        }

        /// <summary>
        /// 保存查询配置的操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="searchId">查询编号</param>
        /// <returns>返回保存成功的js提醒</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult SaveSearchConfig(string id, int searchId = 0)
        {
            var search = new SearchInfo
            {
                Id = searchId,
                TableName = id,
                Title = this.Request.Params["Title"],
                SortColumns = this.Request.Params["SortColumns"],
                VisibleColumns = this.Request.Params["VisibleColumns"]
            };

            this.DynamicQuery.CreateOrUpdate(search);

            return Alert("查询配置成功！");
        }

        /// <summary>
        /// 保存查询条件配置的操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="conditions">查询条件配置信息</param>
        /// <returns>返回保存查询条件配置成功的js</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult SaveConditionConfig(string id, IList<ConditionInfo> conditions)
        {
            this.DynamicQuery.Where<ConditionInfo>(m => m.TableName, id).Remove();

            if (!conditions.IsEmpty())
            {
                foreach (var item in conditions)
                {
                    this.DynamicQuery.Create(item);
                }
            }

            return Alert("查询条件配置成功！");
        }

        /// <summary>
        /// 保存排序配置的操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="orders">排序配置信息</param>
        /// <returns>返回保存排序配置成功的js</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult SaveOrderConfig(string id, IList<OrderInfo> orders)
        {
            this.DynamicQuery.Where<OrderInfo>(m => m.TableName, id).Remove();

            if (!orders.IsEmpty())
            {
                foreach (var item in orders)
                {
                    this.DynamicQuery.Create(item);
                }
            }

            return Alert("排序规则设置成功！");
        }

        #endregion

        #region 添加/编辑配置

        /// <summary>
        /// 显示添加/编辑配置页面的操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <returns>返回添加/编辑配置页面</returns>
        public ActionResult ShowCreateOrUpdateConfig(string id)
        {
            var model = new CreateOrUpdateConfigModel
            {
                Table = this.DynamicQuery.Provider.DbMetadata.GetTable(id)
            };

            if (model.Table != null)
            {
                model.Columns = this.DynamicQuery.Where<CreateOrUpdateColumn>(m => m.TableName, id).List();

                if (model.Columns.IsEmpty())
                {
                    var metaColumns = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);

                    model.Columns = metaColumns.Select(c => new CreateOrUpdateColumn
                    {
                        Name = c.Name,
                        Column = c.Name,
                        PropertyName = c.PropertyName,
                        ColumnLabel = c.Description,
                        Sort = c.Sort,
                        Visible = true,
                        IsPrimaryKey = c.IsPrimaryKey,
                        IsIdentity = c.IsIdentity,
                        Description = c.Description
                    });
                }

                model.Dictionaries = this.DynamicQuery.Where<Dictionary>(m => m.ParentId, null, Op.IsNull).OrderBy(m => m.Sort).List();
            }

            return View(model);
        }

        /// <summary>
        /// 保存添加/编辑配置信息。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="createOrUpdates">添加/编辑配置信息</param>
        /// <returns>返回配置信息保存成功的js</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCreateOrUpdateConfig(string id, IList<CreateOrUpdateInfo> createOrUpdates)
        {
            if (!createOrUpdates.IsEmpty())
            {
                foreach (var item in createOrUpdates)
                {
                    this.DynamicQuery.CreateOrUpdate(item);
                }
            }

            return CloseDialogWithAlert("添加/编辑配置成功！");
        }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/DynamicPage/Controllers/DynamicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.Dynamic.Entities;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Prime.Core;
using Mercurius.Prime.Core.Dynamic;
using Mercurius.Sparrow.Backstage.Areas.DynamicPage.Models.Configuration;
using Mercurius.Sparrow.Backstage.Areas.DynamicPage.Models.Dynamic;
using static Mercurius.Prime.Core.SystemConfiguration;

namespace Mercurius.Sparrow.Backstage.Areas.DynamicPage.Controllers
{
    /// <summary>
    /// 动态页面处理控制器。
    /// </summary>
    public class DynamicController : BaseController
    {
        /// <summary>
        /// 数据查询操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="conditions">查询条件配置信息</param>
        /// <param name="pageIndex">当前页</param>
        /// <returns>返回数据查询页面</returns>
        public ActionResult Index(string id, IList<ConditionInfo> conditions = null, int pageIndex = 1)
        {
            var model = new SearchModel
            {
                Table = this.DynamicQuery.Provider.DbMetadata.GetTable(id)
            };

            if (model.Table != null)
            {
                model.Columns = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);
                model.Search = this.DynamicQuery.Where<SearchInfo>(m => m.TableName, id).Single();
                model.Conditions = this.DynamicQuery.Where<ConditionInfo>(m => m.TableName, id).List();

                var showColumns = model.Search?.GetVisibleColumns();
                var orders = this.DynamicQuery.Where<OrderInfo>(m => m.TableName, id).List().Select(o => (Order)o);

                int totalRecords;
                if (conditions.IsEmpty())
                {
                    model.DataSource = this.DynamicQuery.OrderBy(orders.ToArray()).PagedList(id, pageIndex < 1 ? 1 : pageIndex, DefaultPageSize, out totalRecords, showColumns);
                }
                else
                {
                    var temps = conditions.Select(c => (Condition)c);

                    model.Conditions = conditions.MergeDatas(model.Conditions, (i1, i2) => i1.Column == i2.Column, (i1, i2) =>
                    {
                        i1.Id = i2.Id;
                        i1.TableName = i2.TableName;
                        i1.Op = i2.Op;
                        i1.ValidateRule = i2.ValidateRule;
                        i1.DictionaryKey = i2.DictionaryKey;
                    }) as IList<ConditionInfo>;

                    model.DataSource = this.DynamicQuery.Where(temps).OrderBy(orders.ToArray()).PagedList(id, pageIndex < 1 ? 1 : pageIndex, DefaultPageSize, out totalRecords, showColumns);
                }

                model.TotalRecords = totalRecords;
            }

            this.ViewBag.Model = model;

            return View();
        }

        /// <summary>
        /// 显示数据添加/编辑页面。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="conditions">查询条件</param>
        /// <returns>返回数据添加/编辑页面</returns>
        [ValidateInput(false)]
        public ActionResult CreateOrUpdate(string id, string conditions)
        {
            var model = new CreateOrUpdateModel
            {
                Table = this.DynamicQuery.Provider.DbMetadata.GetTable(id)
            };

            if (model.Table != null)
            {
                model.Columns = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);
                model.CreateOrUpdates = this.DynamicQuery.Where<CreateOrUpdateColumn>(m => m.TableName, id).List();

                model.MergeCreateOrUpdateItems();

                if (!string.IsNullOrWhiteSpace(conditions))
                {
                    model.Conditions = conditions.AsObject<IList<Condition>>();
                    model.DataSource = this.DynamicQuery.Where(model.Conditions).Single(id);
                }
            }

            return View(model);
        }

        /// <summary>
        /// 保存数据添加/编辑的操作。
        /// </summary>
        /// <param name="table">表名称</param>
        /// <returns>返回数据查询页面</returns>
        [HttpPost]
        [ValidateInput(false)]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult Save(string table)
        {
            this.DynamicQuery.CreateOrUpdate(table, this.Request.Params);

            return RedirectToAction("Index", new { @id = table });
        }

        /// <summary>
        /// 删除数据的操作。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="conditions">删除条件</param>
        /// <returns>返回删除成功的json</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Remove(string id, string conditions)
        {
            this.DynamicQuery.Where(conditions.AsObject<IList<Condition>>()).Remove(id);

            return Json(new { Success = true });
        }

        /// <summary>
        /// 查看数据。
        /// </summary>
        /// <param name="id">表名称</param>
        /// <param name="conditions">查询条件</param>
        /// <returns>返回数据查看页面</returns>
        public ActionResult ViewDetail(string id, string conditions)
        {
            var model = new CreateOrUpdateModel
            {
                Table = this.DynamicQuery.Provider.DbMetadata.GetTable(id)
            };

            if (model.Table != null)
            {
                model.Columns = this.DynamicQuery.Provider.DbMetadata.GetColumns(id);
                model.CreateOrUpdates = this.DynamicQuery.Where<CreateOrUpdateColumn>(m => m.TableName, id).List();

                model.MergeCreateOrUpdateItems();

                if (!string.IsNullOrWhiteSpace(conditions))
                {
                    model.Conditions = conditions.AsObject<IList<Condition>>();
                    model.DataSource = this.DynamicQuery.Where(model.Conditions).Single(id);
                }
            }

            return View(model);
        }
    }
}

Mercurius.Sparrow.Backstage/Areas/DynamicPage/Views/Dynamic/Index.cshtml
@using Mercurius.Sparrow.Backstage.Areas.DynamicPage.Models.Dynamic

@{
    var searchModel = this.ViewBag.Model as SearchModel;
}

@if (searchModel.Table != null)
{
    var routeValues = new RouteValueDictionary();
    var primaryKeys = searchModel.Columns.Where(s => s.IsPrimaryKey);
    var showColumns = searchModel.GetSortedColumns().Where(s => !s.IsPrimaryKey && searchModel.IsColumnVisible(s.Name));

    @section Styles{
        <style type="text/css">
            .form-horizontal .form-group {
                margin-bottom: 5px;
            }

                .form-horizontal .form-group .control-label {
                    padding-right: 5px;
                }

                .form-horizontal .form-group .col-sm-2,
                .form-horizontal .form-group .col-sm-10 {
                    padding-left: 5px;
                }

            [validate-rule*=date],
            [validate-rule=time] {
                cursor: pointer;
            }
        </style>
    }

    @section Scripts{
        @Scripts.Render("~/bundles/validate")
        <script type="text/javascript">
            $(document).ready(function () {
                mercurius.ShowDatePicker();
                mercurius.ApplyTableStyle("@string.Format("#dt{0}", searchModel.Table.Name)");
            });

            function edit() {
                var selectedItems = $('@string.Format("#dt{0}", searchModel.Table.Name)').find(' > tbody > tr.selected:not(.empty)');

                if (selectedItems.length == 1) {
                    var selectedValue = selectedItems.find('td:eq(@(showColumns.Count() + 1))').text().trim();
                    var conditions = '[' + selectedValue + ']';

                    $('#conditions').val(conditions);

                    $('#frmEdit').submit();
                } else if (selectedItems.length == 0) {
                    mercurius.ShowWarningMessage('未选中任何一行');
                }
            }

            function Delete() {
                var selectedItems = $('@string.Format("#dt{0}", searchModel.Table.Name)').find(' > tbody > tr.selected:not(.empty)');

                if (selectedItems.length == 1) {
                    mercurius.ShowConfirmMessage('是否确定删除？', function () {
                        var selectedValue = selectedItems.find('td:eq(@(showColumns.Count() + 1))').text().trim();
                        var conditions = '[' + selectedValue + ']';

                        $.ajax({
                            url: '@Url.Action("Remove")',
                            type: 'POST',
                            cache: false,
                            data: { id: '@string.Format("{0}.{1}", searchModel.Table.Schema,searchModel.Table.Name)', conditions: conditions },
                            dataType: 'JSON',
                            complete: function (rs) {
                                if (rs.status == 200) {
                                    mercurius.ShowTipsMessage('删除成功！', 5000, 4);

                                    window.location.reload();
                                } else {
                                    mercurius.ShowTipsMessage('删除失败，请稍后重试！', 5000, 5);
                                }
                            }
                        });
                    });
                } else if (selectedItems.length == 0) {
                    mercurius.ShowWarningMessage('未选中任何一行');
                }
            }

            function detail() {
                var selectedItems = $('@string.Format("#dt{0}", searchModel.Table.Name)').find(' > tbody > tr.selected:not(.empty)');

                if (selectedItems.length == 1) {
                    var selectedValue = selectedItems.find('td:eq(@(showColumns.Count() + 1))').text().trim();
                    var conditions = '[' + selectedValue + ']';

                    $('#conditions').val(conditions);

                    $('#frmEdit').prop('action', '@Url.Action("ViewDetail")');
                    $('#frmEdit').submit();
                } else if (selectedItems.length == 0) {
                    mercurius.ShowWarningMessage('未选中任何一行');
                }
            }
        </script>
    }
    <div class="header">@searchModel.GetTitle()</div>
    if (!searchModel.Conditions.IsEmpty())
    {
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="form-horizontal" role="form">
                    @using (Html.BeginForm("Index", "Dynamic", FormMethod.Post, new { @id = "frmSearch", @autocomplete = "off" }))
                    {
                        var index = 0;
                        var count = searchModel.Conditions.Count;
                        var groupCount = count % 4 == 0 ? count / 4 : (count / 4) + 1;
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="Id" value="@string.Format("{0}.{1}",searchModel.Table.Schema, searchModel.Table.Name)" />for (var i = 1; i <= groupCount; i++)
                        {
                            <div class="form-group">
                                @for (; index < i * 4 && index < count; index++)
                                {
                                    var item = searchModel.Conditions[index];

                                    <input type="hidden" name="@string.Format("conditions[{0}].Column",index)" value="@item.Column" />
                                    <input type="hidden" name="@string.Format("conditions[{0}].Op",index)" value="@item.Op" />
                                    <label class="col-sm-1 control-label" for="@string.Format("control{0}", item.Id)">
                                        @searchModel.GetColumnDescription(item.Column)
                                    </label>
                                    <div class="col-sm-2">
                                        @if (!string.IsNullOrWhiteSpace(item.DictionaryKey))
                                        {
                                            @Html.MultipleList(string.Format("conditions[{0}].Value", index), item.DictionaryKey, f=>f.Value(item.Value).IncludeAll().Form(new { @id = string.Format("control{0}", item.Id) }))
                                        }
                                        else
                                        {
                                            <input type="text" id="@string.Format("control{0}", item.Id)" name="@string.Format("conditions[{0}].Value", index)" class="form-control" value="@item.Value" @(string.IsNullOrWhiteSpace(item.ValidateRule) ? string.Empty : string.Format("validate-rule={0} validate-field={1}", item.ValidateRule, searchModel.GetColumnDescription(item.Column))) />
                                        }
                                    </div>
                                    routeValues.Add(string.Format("conditions[{0}].Column", index), item.Column);
                                    routeValues.Add(string.Format("conditions[{0}].Op", index), item.Op.ToString());
                                    routeValues.Add(string.Format("conditions[{0}].Value", index), item.Value);
                                }
                            </div>
                        }
                        <div class="form-group form-group-sm">
                            <label class="col-sm-1"></label>
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">
                                    <i class="glyphicon glyphicon-search"></i> 查询
                                </button>
                                <button type="button" class="btn btn-default" onclick="$('#frmSearch [name]:visible').val('');">
                                    <i class="glyphicon glyphicon-remove"></i> 重置
                                </button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
    <div class="toolbar panel panel-default">
        <div class="panel-heading">
            <div class="right">
                <form id="frmEdit" action="@Url.Action("CreateOrUpdate")" method="post" class="btn-group" style="display:inline;">
                    <input name="id" type="hidden" value="@string.Format("{0}.{1}", searchModel.Table.Schema,searchModel.Table.Name)" />
                    <input id="conditions" name="conditions" type="hidden" />
                    @if (!searchModel.Table.IsView)
                    {
                        <a href="@Url.Action("CreateOrUpdate", new { @id = string.Format("{0}.{1}", searchModel.Table.Schema,searchModel.Table.Name)})" class="btn btn-default">
                            <i class="glyphicon glyphicon-plus"></i> 添加
                        </a>
                        <button type="button" class="btn btn-default" style="display:inline;" onclick="edit();">
                            <i class="glyphicon glyphicon-edit"></i> 编辑
                        </button>
                    }
                    <button type="button" class="btn btn-default" style="display: inline;" onclick="detail();">
                        <i class="glyphicon glyphicon-list-alt"></i> 详情
                    </button>
                    @if (!searchModel.Table.IsView)
                    {
                        <a class="btn btn-default" onclick="Delete();">
                            <i class="glyphicon glyphicon-remove"></i> 删除
                        </a>
                    }
                    <a class="btn btn-default" href="@Url.Action("Index", "Configuration")">
                        <i class="glyphicon glyphicon-chevron-left"></i> 返回
                    </a>
                </form>
            </div>
        </div>
    </div>
    <table id="@string.Format("dt{0}", searchModel.Table.Name)" class="grid">
        <thead>
            <tr>
                <td style="width: 40px; text-align: center;">
                    <label class="check-all" title="全选"></label>
                </td>
                @foreach (var item in showColumns)
                {
                    <td>@item.Description</td>
                }
            </tr>
        </thead>
        <tbody>
            @if (searchModel.DataSource.Rows.Count == 0)
            {
                <tr class="empty">
                    <td colspan="@(showColumns.Count() + 1)" class="empty-data">
                        @Html.GetGlobalValue("empty-data")
                    </td>
                </tr>
            }
            else
            {
                foreach (DataRow row in searchModel.DataSource.Rows)
                {
                    <tr>
                        <td style="width: 40px; text-align: center;">@row[0]</td>
                        @foreach (var item in showColumns)
                        {
                            <td>@row[item.Name]</td>
                        }
                        <td style="display: none;">
                            @{
                                var viewColumns = primaryKeys.IsEmpty() ? searchModel.Columns.Where(c => c.DataType != "datetime") : primaryKeys;

                                foreach (var item in viewColumns)
                                {
                                    <text>{PropertyName:'@item.Name',Value:'@row[item.Name]'}</text>@(item == viewColumns.Last() ? string.Empty : ",")
                                }
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    @Html.Paging(searchModel.TotalRecords, routeValues: routeValues)
}

Mercurius.Sparrow.Backstage/Areas/DynamicPage/Views/Dynamic/ViewDetail.cshtml
@using Mercurius.Sparrow.Backstage.Areas.DynamicPage.Models.Dynamic

@model CreateOrUpdateModel

@section Styles{
    <style type="text/css">
        .form-control {
            height: auto;
            min-height: 34px;
            max-height: 200px;
            overflow: auto;
        }
    </style>
}
@if (Model.Table != null)
{
    var columns = Model.CreateOrUpdates;
    var showColumns = columns.Where(s => !s.IsPrimaryKey);

    <div class="header">
        查看@(Model.Table.Comments)信息
    </div>
    <div class="form-horizontal" style="margin-top:10px;">
        @foreach (var item in showColumns)
        {
            if (item.Visible == true)
            {
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="@item.Column">
                        @item.ColumnLabel
                    </label>
                    <div class="col-sm-8">
                        @if (string.IsNullOrWhiteSpace(item.DictionaryKey))
                        {
                            <span class="form-control">@Model.GetValue(item.Name)</span>
                        }
                        else
                        {
                            @Html.MultipleList(item.Column, item.DictionaryKey, f=>f.Value(Model.GetValue(item.Name)).Disabled())
                        }
                    </div>
                </div>
            }
        }
        <div class="form-group form-group-sm">
            <label class="col-sm-2">&nbsp;</label>
            <div class="col-sm-8">
                <a href="@Url.Action("Index", new { @id = string.Format("{0}.{1}", Model.Table.Schema, Model.Table.Name) })" class="btn btn-default">
                    <i class="glyphicon glyphicon-chevron-left"></i> 返回
                </a>
            </div>
        </div>
    </div>
}