Mercurius.Sparrow.Backstage/Areas/Admin/Models/User/CreateOrUpdateVM.cs
using System.Collections.Generic;
using System.Linq;
using UserInfo = Mercurius.Kernel.Contracts.RBAC.Entities.User;

namespace Mercurius.Sparrow.Backstage.Areas.Admin.Models.User
{
    /// <summary>
    /// 添加或者编辑用户信息视图模型。
    /// </summary>
    public class CreateOrUpdateVM
    {
        #region 字段

        private IList<string> _checkValues;

        #endregion

        #region 属性

        /// <summary>
        /// 用户信息。
        /// </summary>
        public UserInfo User { get; set; }

        /// <summary>
        /// 选择项。
        /// </summary>
        public IList<string> CheckValues
        {
            get
            {
                return this._checkValues;
            }

            set
            {
                if (this._checkValues != value)
                {
                    this._checkValues = value;

                    var values = from v in value
                                 let vs = v.Split('|')
                                 group vs[0] by vs[1] into g
                                 select g;

                    foreach (var item in values)
                    {
                        switch (item.Key)
                        {
                            case "所属部门":
                                this.Departments = item.ToArray();

                                break;

                            case "所属角色":
                                this.Roles = item.ToArray();

                                break;
                        }
                    }
                }
            }
        }

        #endregion

        #region 业务属性

        /// <summary>
        /// 所属部门。
        /// </summary>
        public string[] Departments { get; private set; }

        /// <summary>
        /// 所属角色。
        /// </summary>
        public string[] Roles { get; private set; }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/Admin/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.RBAC.SearchObjects;
using Mercurius.Kernel.Contracts.RBAC.Services;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Prime.Core;
using Mercurius.Sparrow.Backstage.Areas.Admin.Models.User;

namespace Mercurius.Sparrow.Backstage.Areas.Admin.Controllers
{
    /// <summary>
    /// 用户管理控制器。
    /// </summary>
    public class UserController : BaseController
    {
        #region 常量

        private const string PasswordReplaceString = "********";
        private const string SessionVerifyCode = "session_verifyCode";

        #endregion

        #region 属性

        /// <summary>
        /// 用户信息服务。
        /// </summary>
        public IUserService UserService { get; set; }

        /// <summary>
        /// 角色信息服务。
        /// </summary>
        public IRoleService RoleService { get; set; }

        /// <summary>
        /// 权限管理服务。
        /// </summary>
        public IPermissionService PermissionService { get; set; }

        /// <summary>
        /// 组织机构服务对象。
        /// </summary>
        public IOrganizationService OrganizationService { get; set; }

        #endregion

        #region 用户信息查询

        /// <summary>
        /// 显示用户信息主界面。
        /// </summary>
        /// <param name="so">搜索条件</param>
        /// <returns>执行结果</returns>
        public ActionResult Index(UserSO so = null)
        {
            return this.View();
        }

        /// <summary>
        /// 获取部门信息。
        /// </summary>
        /// <returns>执行结果</returns>
        public ActionResult Departments()
        {
            this.ViewBag.Organizations = this.OrganizationService.GetOrganizations();

            return this.View();
        }

        /// <summary>
        /// 获取用户信息。
        /// </summary>
        /// <param name="so">用户信息查询对象</param>
        /// <returns>执行结果</returns>
        public ActionResult Users(UserSO so = null)
        {
            var rspUsers = this.UserService.SearchUsers(so);

            this.ViewBag.SO = so;
            this.ViewBag.ResponseUsers = rspUsers;

            return this.View();
        }

        #endregion

        #region 单个用户信息处理

        /// <summary>
        /// 添加或编辑用户信息界面。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>执行结果</returns>
        public ActionResult CreateOrUpdate(string id)
        {
            var model = new CreateOrUpdateVM
            {
                User = this.UserService.GetUserById(id).Data
            };

            if (model.User != null)
            {
                this.ViewBag.RealPassword = model.User.Password;

                model.User.Password = PasswordReplaceString;
            }

            this.ViewBag.Roles = this.RoleService.GetRoles();
            this.ViewBag.Departments = this.OrganizationService.GetOrganizations();

            return this.View(model);
        }

        /// <summary>
        /// 提交用户信息。
        /// </summary>
        /// <param name="vm">添加或编辑用户信息视图模型</param>
        /// <returns>执行结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrUpdate(CreateOrUpdateVM vm)
        {
            vm.User.Initialize();

            if (string.IsNullOrWhiteSpace(vm.User.Id))
            {
                vm.User.Id = Guid.NewGuid().ToString();
            }

            vm.CheckValues = this.Request.Params["CheckValues"].Split(',').ToList();
            vm.User.Password = vm.User.Password == PasswordReplaceString ? this.Request.Form["RealPassword"] : vm.User.Password.Encrypt();

            var rsp = this.UserService.CreateOrUpdate(vm.User, vm.Departments, vm.Roles);

            return rsp.IsSuccess ? this.CloseDialogWithAlert("保存成功！") : this.Alert($"发生错误，错误原因：{rsp.ErrorMessage}", AlertType.Error);
        }

        /// <summary>
        /// 删除用户信息。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>删除结果信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Remove(string id)
        {
            var rsp = this.UserService.Remove(id);

            return Json(rsp);
        }

        /// <summary>
        /// 授权用户。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>执行结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult AuthorizeUser(string id)
        {
            var rsp = this.UserService.ChangeStatus(id, 1);

            return this.Json(rsp.IsSuccess);
        }

        /// <summary>
        /// 锁定用户。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>执行结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult LockUser(string id)
        {
            var rsp = this.UserService.ChangeStatus(id, 2);

            return this.Json(rsp.IsSuccess);
        }

        #endregion

        /// <summary>
        /// 查看用户详情。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>用户详情界面</returns>
        public ActionResult ViewDetails(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                id = WebHelper.GetLogOnUserId();
                this.ViewBag.Source = "ViewCurrent";
            }
            else
            {
                this.ViewBag.Source = this.Request.Params["Source"];
            }
            
            this.ViewBag.User = this.UserService.GetUserById(id);
            this.ViewBag.Roles = this.RoleService.GetRolesById(id);
            this.ViewBag.Permissions = this.PermissionService.GetSystemMenusWithAllotedByUser(id);
            this.ViewBag.RepoterAndSubordinates = this.UserService.GetRepoterAndSubordinates(id);

            return View();
        }

        #region 修改密码

        /// <summary>
        /// 显示修改密码界面。
        /// </summary>
        /// <returns>操作结果</returns>
        public ActionResult ChangePassword()
        {
            return this.View();
        }

        /// <summary>
        /// 修改密码操作。
        /// </summary>
        /// <param name="oldPassword">旧密码</param>
        /// <param name="newPassword">新密码</param>
        /// <param name="verifyCode">验证码</param>
        /// <returns>操作结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult ChangePassword(string oldPassword, string newPassword, string verifyCode)
        {
            string message;
            var isSuccess = false;

            if (string.Compare(verifyCode, Convert.ToString(this.Session[SessionVerifyCode]), StringComparison.OrdinalIgnoreCase) == 0)
            {
                var rsp = this.UserService.ChangePassword(WebHelper.GetLogOnUserId(), oldPassword, newPassword);

                isSuccess = rsp.IsSuccess;
                message = rsp.ErrorMessage;
            }
            else
            {
                message = "验证码不正确！";
            }

            return this.Json(new { IsSuccess = isSuccess, Message = message });
        }

        #endregion

        #region 权限管理

        /// <summary>
        /// 显示用户授权界面。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <param name="userName">用户名称</param>
        /// <returns>显示用户授权界面</returns>
        public ActionResult AllotPermissions(string id, string userName)
        {
            this.ViewBag.Id = id;
            this.ViewBag.UserName = userName;

            var rsp = this.PermissionService.GetSystemMenusWithAllotedByUser(id);

            return View(rsp);
        }

        /// <summary>
        /// 保存用户权限信息。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <param name="selecteds">选择的权限编号</param>
        /// <returns>保存结果信息</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult ConfirmAllotPermissions(string id, string selecteds)
        {
            var rsp = this.PermissionService.AllotPermissionByRole(id, selecteds.Split(','));

            return Json(rsp);
        }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/WebApi/Controllers/UserController.cs
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.WebApi.Entities;
using Mercurius.Kernel.Contracts.WebApi.SearchObjects;
using Mercurius.Kernel.Contracts.WebApi.Services;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Prime.Core;

namespace Mercurius.Sparrow.Backstage.Areas.WebApi.Controllers
{
    /// <summary>
    /// 用户信息管理控制器。
    /// </summary>
    public class UserController : BaseController
    {
        #region 属性

        /// <summary>
        /// Web API用户信息服务对象。
        /// </summary>
        public IUserService UserService { get; set; }

        #endregion

        /// <summary>
        /// 用户管理首页。
        /// </summary>
        /// <returns>首页视图</returns>
        public ActionResult Index(UserSO so)
        {
            var model = this.UserService.SearchUsers(so);

            return View(model);
        }

        /// <summary>
        /// 添加或者修改用户信息页面。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>视图</returns>
        public ActionResult CreateOrUpdate(int? id = null)
        {
            if (id != null)
            {
                var rsp = this.UserService.GetUserById(id.Value);

                return View(rsp.Data);
            }

            return View();
        }

        /// <summary>
        /// 保存修改。
        /// </summary>
        /// <param name="user">用户信息</param>
        /// <returns>保存结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrUpdate(User user)
        {
            if (user.IsValid())
            {
                if (user.Password != "******")
                {
                    user.ChangePassword = true;
                }

                user.Password = user.Password.MD5();

                var rsp = this.UserService.CreateOrUpdate(user);

                if (rsp.IsSuccess)
                {
                    return CloseDialogWithAlert("保存成功！");
                }
            }

            return Alert("添加失败！", AlertType.Error);
        }

        /// <summary>
        /// 删除用户信息。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>操作结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult Remove(int id)
        {
            var rsp = this.UserService.Remove(id);

            return Json(rsp);
        }

        /// <summary>
        /// 用户授权
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>锁定结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult AuthorizeUser(int id)
        {
            return Json(this.UserService.ChangeStatus(id, 1));
        }

        /// <summary>
        /// 锁定用户。
        /// </summary>
        /// <param name="id">用户编号</param>
        /// <returns>锁定结果</returns>
        [HttpPost]
        [IgnorePermissionValid]
        public ActionResult LockUser(int id)
        {
            return Json(this.UserService.ChangeStatus(id, 2));
        }
    }
}

Mercurius.Sparrow.Backstage/Controllers/HelperController.cs
using System.Linq;
using System.Web.Mvc;
using Mercurius.Kernel.Contracts.RBAC.SearchObjects;
using Mercurius.Kernel.Contracts.RBAC.Services;
using Mercurius.Kernel.Contracts.Storage.Entities;
using Mercurius.Kernel.Implementations.Storage.WebApi;
using Mercurius.Kernel.WebCores.Filters;
using Mercurius.Kernel.WebCores.HtmlHelpers;
using Mercurius.Prime.Core;

namespace Mercurius.Sparrow.Backstage.Controllers
{
    /// <summary>
    /// 帮助控制器。
    /// </summary>
    public class HelperController : BaseController
    {
        #region 常量

        private static readonly string FileUploadError = "error|上传失败";

        #endregion

        #region 属性

        /// <summary>
        /// 用户服务接口。
        /// </summary>
        public IUserService UserService { get; set; }

        /// <summary>
        /// 文件上传Web Api客户端。
        /// </summary>
        public FileStorageClient FileStorageClient { get; set; }

        /// <summary>
        /// 组织机构服务接口。
        /// </summary>
        public IOrganizationService OrganizationService { get; set; }


        #endregion

        /// <summary>
        /// wangEdit文件上传。
        /// </summary>
        /// <returns>上传结果</returns>
        [IgnorePermissionValid]
        public ActionResult Upload()
        {
            if (this.Request.Files.Count == 0)
            {
                return Content(FileUploadError);
            }

            var rsp = this.FileStorageClient.Upload(WebHelper.GetLogOnAccount(), this.Request);

            return Content(string.IsNullOrWhiteSpace(rsp.Datas?.FirstOrDefault()) ? FileUploadError + rsp.ErrorMessage : Url.GetFileUrl(rsp.Datas.FirstOrDefault(), CompressMode.Medium));
        }

        /// <summary>
        /// 显示图标选择界面。
        /// </summary>
        /// <returns>图标显示界面</returns>
        [IgnorePermissionValid]
        public ActionResult ChooseImage()
        {
            return this.View();
        }

        #region 用户选择

        /// <summary>
        /// 选择用户界面。
        /// </summary>
        /// <param name="so">用户查询</param>
        /// <returns>显示界面</returns>
        [IgnorePermissionValid]
        public ActionResult ChooseUser(UserSO so)
        {
            so = so ?? new UserSO();
            so.PageSize = 10;

            this.ViewBag.SO = so;
            this.ViewBag.Type = this.Request.Params["type"];
            this.ViewBag.Organizations = this.OrganizationService.GetOrganizations();
            this.ViewBag.Users = this.UserService.SearchUsers(so);

            return View();
        }

        /// <summary>
        /// 获取用户信息。
        /// </summary>
        /// <param name="so">用户查询</param>
        /// <returns>显示界面</returns>
        [IgnorePermissionValid]
        public ActionResult GetUsers(UserSO so)
        {
            so.PageSize = 10;
            var rspUsers = this.UserService.SearchUsers(so);

            this.ViewBag.SO = so;
            this.ViewBag.Type = this.Request.Params["type"];

            return PartialView("_ChooseUsers", rspUsers);
        }

        #endregion
    }
}

Mercurius.Sparrow.Backstage/Areas/Admin/Views/User/CreateOrUpdate.cshtml
@using Mercurius.Sparrow.Backstage.Areas.Admin.Models.User

@model CreateOrUpdateVM

@{
    var roles = this.ViewBag.Roles as ResponseSet<Role>;
    var departments = this.ViewBag.Departments as ResponseSet<Organization>;
}

@section Styles{
    @Styles.Render("~/Content/tree/css")
    <style type="text/css">
        .tab-pane {
            padding-top: 5px;
        }

        .treeview label {
            cursor: pointer;
            font-weight: normal;
        }
    </style>
}

@section Scripts
{
    @Scripts.Render("~/bundles/tree", "~/bundles/validate")
    <script type="text/javascript">
        $(document).ready(function () {
            $('a[data-toggle="tab"]').one('shown.bs.tab', function (e) {
                if (e.target.text == '所属部门') {
                    $('#departmentContainer').treeview({
                        persist: "location",
                        collapsed: false,
                        unique: false
                    });
                }

                if (e.target.text == '所属角色') {
                    $('#roleContainer').treeview({
                        persist: "location",
                        collapsed: false,
                        unique: true
                    });
                }
            });

            $('#reporterName').click(function () {
                mercurius.OpenDialog('@Url.Action("ChooseUser", "Helper",new { Area="" ,ExcludeReporter = (Model ==null || Model.User==null) ? "" : Model.User.Id })', 'ChooseUser', '选择用户', 720, 500, { statusbar: false, x: 'right', y: 'bottom' });
            });
        });

        //获取表单值
        function OnSave() {
            var checkedOrgCount = $('#table2 label > :checkbox:checked').length;

            if (checkedOrgCount == 0) {
                mercurius.ShowWarningMessage("点击面板所属部门，选择部门！");
            } else if (JudgeValidate('#frmSave')) {
               $('#frmSave').submit();
            }
        }

        function SetUser(reporterId, reporterName) {
            $('#reporterId').val(reporterId);
            $('#reporterName').val(reporterName);
        }
    </script>
}
@using (Ajax.BeginForm("CreateOrUpdate", "User", null, new AjaxOptions { HttpMethod = "POST" }, new { @id = "frmSave", @class = "form-horizontal form", @role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.User.Id)
    @Html.Hidden("RealPassword", this.ViewData["RealPassword"])
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a href="#table1" role="tab" data-toggle="tab">基本信息</a></li>
        <li><a href="#table2" role="tab" data-toggle="tab">所属部门</a></li>
        <li><a href="#table3" role="tab" data-toggle="tab">所属角色</a></li>
    </ul>
    <div class="tab-content">
        @*基本信息*@
        <div id="table1" class="tab-pane active">
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_Code">工号</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(m => m.User.Code, new { @class = "form-control", @readonly="readonly" })
                </div>
                <label class="col-sm-2 control-label" for="User_Name">姓名</label>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.User.Name, new { @class = "form-control", @validate_field = "姓名", @validate_rule = "notNull" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_Account">账号</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(m => m.User.Account, new { @class = "form-control", @validate_field = "账号", @validate_rule = "notNull" })
                </div>
                <label class="col-sm-2 control-label" for="User_Password">密码</label>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.User.Password, new { @class = "form-control", @validate_field = "密码", @validate_rule = "notNull" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_Sex">性别</label>
                <div class="col-sm-3">
                    <label class="radio-inline">
                        <input name="User.Sex" type="radio" value="1" @(Model!=null && Model.User!=null&&Model.User.Sex==1?"checked":"")/> 男
                    </label>
                    <label class="radio-inline">
                        <input name="User.Sex" type="radio" value="0" @(Model!=null && Model.User!=null&&Model.User.Sex==0?"checked":"")/> 女
                    </label>
                </div>
                <label class="col-sm-2 control-label" for="User_Email">电子邮件</label>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.User.Email, new { @class = "form-control", @validate_field = "电子邮箱", @validate_rule = "emailOrNull" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_Title">职称</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(m => m.User.Title, new { @class = "form-control" })
                </div>
                <label class="col-sm-2 control-label" for="reporterName">报告人</label>
                <div class="col-sm-4">
                    @Html.HiddenFor(m => m.User.Reporter, new { @id = "reporterId" })
                    @Html.TextBoxFor(m => m.User.ReporterName, new { @id = "reporterName", @class = "form-control", @readonly = "readonly" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_Remark">备注描述</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.User.Remark, new { @class = "form-control", @style = "height: 90px;" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_CreateUserName">创建用户</label>
                <div class="col-sm-3">
                    <input id="CreateUserName" value="@WebHelper.GetLogOnAccount()" class="form-control" disabled />
                </div>
                <label class="col-sm-2 control-label" for="User_CreateDateTime">创建时间</label>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.User.CreateDateTime, new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>
            <div class="form-group form-group-sm">
                <label class="col-sm-2 control-label" for="User_ModifyUserName">修改用户</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(m => m.User.ModifyUserName, new { @class = "form-control", @disabled = "disabled" })
                </div>
                <label class="col-sm-2 control-label">修改时间</label>
                <div class="col-sm-4">
                    @Html.TextBoxFor(m => m.User.ModifyDateTime, new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>
        </div>
        @*所属部门*@
        <div id="table2" class="tab-pane">
            <div class="header">组织机构</div>
            <div style="height: 250px; overflow-y: auto;">
                <ul id="departmentContainer" class="filetree">
                    @{
                        var departmentParents = departments.Datas.Where(o => o.ParentId == "0");

                        foreach (var parent in departmentParents)
                        {
                            <li>
                                <span class="folder"></span>
                                <label>
                                    <input name="CheckValues" type="checkbox" @IsChecked((Model != null && Model.User != null) ? Model.User.Departments : null, parent.Id) value="@parent.Id|所属部门" />
                                    @parent.Name
                                </label>
                                @CreateDepartmentTreeNode(departments.Datas, parent.Id)
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
        @*所属角色*@
        <div id="table3" class="tab-pane">
            <div class="header">所属角色</div>
            <div style="height: 250px; overflow-y: auto;">
                <ul id="roleContainer" class="filetree">
                    @{
                        var roleParents = roles.Datas.Where(r => r.ParentId == "0");

                        foreach (var roleParent in roleParents)
                        {
                            <li>
                                <span class="folder"></span>
                                <label>
                                    <input name="CheckValues" type="checkbox" @IsChecked((Model != null && Model.User != null) ? Model.User.Roles : null, roleParent.Id) value="@roleParent.Id|所属角色" />
                                    @roleParent.Name
                                </label>
                                @CreateRoleTreeNode(roles.Datas, roleParent.Id)
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
}

@helper CreateDepartmentTreeNode(IList<Organization> datas, string parentId)
{
    var children = datas.Where(d => d.ParentId == parentId);

    if (children.Any())
    {
        <ul>
            @foreach (var child in children)
            {
                <li>
                    <span class="file"></span>
                    <label>
                        <input name="CheckValues" type="checkbox" @IsChecked((Model != null && Model.User != null) ? Model.User.Departments : null, child.Id) value="@child.Id|所属部门" />
                        @child.Name
                    </label>

                    @CreateDepartmentTreeNode(datas, child.Id)
                </li>
            }
        </ul>
    }
}
@helper CreateRoleTreeNode(IList<Role> roles, string parentId)
{
    var children = roles.Where(d => d.ParentId == parentId);

    if (children.Any())
    {
        <ul>
            @foreach (var child in children)
            {
                <li>
                    <span class="file"></span>
                    <label>
                        <input name="CheckValues" type="checkbox" @IsChecked((Model != null && Model.User != null) ? Model.User.Roles : null, child.Id) value="@child.Id|所属角色" />
                        @child.Name
                    </label>
                    @CreateRoleTreeNode(roles, child.Id)
                </li>
            }
        </ul>
    }
}
@helper IsChecked(IList<string> sources, string id)
{
    if (!sources.IsEmpty() && sources.Contains(id))
    {
        <text>checked="checked"</text>
    }
}

Mercurius.Sparrow.Backstage/Areas/Admin/Views/User/Departments.cshtml
@using Mercurius.Prime.Core.Entities
@{
    var organizations = this.ViewBag.Organizations as ResponseSet<Organization>;
}

@section Styles
{
    @Styles.Render("~/Content/tree/css")
}

@section Scripts
{
    @Scripts.Render("~/bundles/tree")
    <script type="text/javascript">
        //初始化
        $(function () {
            $('#treeContainer').treeview({
                collapsed: false,
                unique: false
            });

            $('#treeContainer li > b').click(function () {
                $('#treeContainer li b').removeClass('selected');

                var path = '@Url.Action("Users")/?OrganizationId=' + $(this).prop('id');
                window.parent.frames["target_right"].location = path;
                $(this).addClass('selected');

                // 取消事件冒泡。
                return false;
            });
        });
    </script>
}
<div class="header">组织机构</div>
<div>
    @if (organizations.HasData())
    {
        @TreeHelper.CreateTree(organizations.Datas.AsTree(o => o.ParentId == "0", (p, c) => c.ParentId == p.Id, o => new TreeNode { Id = o.Id, Text = o.Name }), "treeContainer")
    }
</div>

Mercurius.Sparrow.Backstage/Areas/Admin/Views/User/Index.cshtml
@section Styles{
    <style type="text/css">
        .col-sm-2, .col-sm-10 {
            margin: 0;
            padding: 0;
            height: 100%;
        }

        .col-sm-2 {
            width: 20%;
        }

        .col-sm-10 {
            width: 80%;
            border: 1px solid #ccc;
        }
    </style>
}

@section Scripts{
    <script type="text/javascript">
        $(function () {
            $("html").css("overflow", "hidden");
            $("body").css("overflow", "hidden");
            iframeresize();
            $("#target_right").attr("src", '@Url.Action("Users")');
            $("#target_left").attr("src", '@Url.Action("Departments")');
        });

        /**自应高度**/
        function iframeresize() {
            function resizeU() {
                var iframeMain = $(window).height();
                $("#iframeMainContent").height(iframeMain);
            }

            resizeU();
            $(window).resize(resizeU);
        }
    </script>
}
<div id="iframeMainContent">
    <div class="pull-left col-sm-2" style="padding-right:1px;">
        <iframe id="target_left" name="target_left" scrolling="auto" frameborder="0" scrolling="yes"
                width="100%" height="100%"></iframe>
    </div>
    <div class="pull-right col-sm-10">
        <iframe id="target_right" name="target_right" scrolling="auto" frameborder="0" scrolling="yes"
                width="100%" height="100%"></iframe>
    </div>
</div>